### ISSUE TITLE
Compatibility with monolog v2.X?

### ISSUE THREAD

**Issue by Jacq** [itspire/monolog-loki#1]
I see the current requirement for monolog-loki is locked to monolog ~1.25, should it be compatible with monolog v2.0?
I do not know about monolog internals or migration needed but this might be related: https://github.com/Seldaek/monolog/issues/903
Thanks!

**Comment by rrajkomar** [comment]
Well that's mostly because I haven't tested it with Monolog 2.0 yet.  
Since the current LTS version of Symfony (4.4) has a requirement on monolog ^1.25.1   
And I only use monolog though the LTS version of Symfony,  
I did not test it with ~2.0.

However, you're welcome to try it in order to check if it works.
And provide a PR if it doesn't as is.
Otherwise, I'll work on a compatible version when an LTS version of Symfony supports the 2.0 version of monolog.

**Comment by Jacq** [comment]
Seems to work fine I have just change the requirement with no other modifications. 
There are details about the upgrade to monolog 2.0 [here](https://github.com/Seldaek/monolog/blob/master/UPGRADE.

I am using the handler embed in a logger provider in Laravel 7.X and I did not notice any important issues.
The only strange behavior is that Loki live mode is not working with this stream I have to check all the others but for the moment this seems the only one not tailing new messages live mode.
Cheers,

If anyone is interested in using in laravel this is an example of the logger provider similar to t[his logstash example](https://medium.com/@bauernfeind.dominik/using-logstash-with-laravel-509c65065d52):
```
<?php

namespace App\Providers;

use Itspire\MonologLoki\Handler\LokiHandler;
use Monolog\Handler\WhatFailureGroupHandler;
use Monolog\Logger;
use Psr\Log\LoggerInterface;

class LokiLoggerProvider
{

    /**
     * @param array $config
     * @return LoggerInterface
     */
    public function __invoke(array $config): LoggerInterface
    {
        $options = [
            'entrypoint' => $config['url'],
            'context' => [
                // Set here your globally applicable context variables
            ],
            'labels' => [
                // Set here your globally applicable labels
                'app' => config('app.name')
            ],
            'client_name' => gethostname(), // Here set a unique identifier for the client host
        ];
        // Optional : if you're using basic auth to authentify
        if (!empty($config['user']) && !empty($config['password'])) {
            $options['auth'] = [
                'basic' => [$config['user'], $config['password']],
            ];
        }
        $handler =new WhatFailureGroupHandler(
            [
                new LokiHandler($options)
            ]);

        return new Logger('loki.main', [$handler]);
    }

}
```

**Comment by rrajkomar** [comment]
> The only strange behavior is that Loki live mode is not working with this stream I have to check all the others but for the moment this seems the only one not tailing new messages live mode.

I had thay issue a while back and after searching a bit on the web I foudn out that it was related to my grafana configuration and that I had to add the following headers to my Loki datasource to enable WebSocket support : 
```
Connection: Upgrade
Upgrade: Websocket
```
Maybe it will solve your issue.

**Comment by rrajkomar** [comment]
Sorry, unexpected side effect from my commit message. 
Was not meant to close the Github issue.
I will adapt so this doesn't happen again.
