### ISSUE TITLE
Handling unreachable Loki server

### ISSUE THREAD

**Issue by KevinBeckers** [itspire/monolog-loki#11]
Hi, thank you for this lib!

I need some guidance regards handeling an unreachable Loki server.
We are using this library with Laravel which works great, it is used as the last of a few handlers.
If for some reason the Loki server is not available, a `RuntimeException` is thrown. This results in exception down the line which is understandable but not convenient. 

What would be the best way of handeling this? Perhaps it would be useful to create a Loki exception and replace the `RuntimeException`, which I could add to the Laravel ignore properties?

**Comment by Jacq** [comment]
What about using one of the special monolog handlers to wrap the loki logger to ignore or retry the logging?, see WhatFailureGroupHandler or the FallbackGroupHandler in https://github.com/Seldaek/monolog/blob/main/doc/02-handlers-formatters-processors.md#wrappers--special-handlers.

**Comment by KevinBeckers** [comment]
Hi Jacq, thank you. This solution is perfect, I learned something today. Would you like me to make a pull request for documentation about this?

**Comment by rrajkomar** [comment]
@KevinBeckers There is actually already the documentation for WhatFailureGroupHandler in the readme of the library.
Granted I only added the native version, as I do not use Laravel personally, but you're welcome to provide a Laravel based example as a PR :slightly_smiling_face:
