### ISSUE TITLE
CURLOPT_RETURNTRANSFER is set to `false`

### ISSUE THREAD

**Issue by cstuder** [itspire/monolog-loki#2]
I'm trying out Loki and am using your library to log to it. When experimenting with an incorrect Loki URL, `monolog-loki` appended the 404 error message to the server output instead of swallowing it. I traced this back to this line:

https://github.com/itspire/monolog-loki/blob/9dac4899137b60c32ceecceb2b248b9f3a74cbcd/src/main/php/Handler/LokiHandler.php#L84

I suggest setting `CURLOPT_RETURNTRANSFER` to `true`.

Is there a particular reason this is set to false?

**Comment by rrajkomar** [comment]
Hi, truth be told, I think I found the inspiration from another library using curl as well.
If the problem is due to the RETURNTRANFER value, and it is an urgent fix, could you provide a PR for it as I won't be able to work on the library within the few nect weeks.

**Comment by cstuder** [comment]
PR opened.
