### ISSUE TITLE
How to change the time?

### ISSUE THREAD

**Issue by l2aelba** [itspire/monolog-loki#25]
I trying to import the old logs to Loki

Is there any function I can change the time?

Thanks.

**Comment by rrajkomar** [comment]
Hi,  
this would be a question more suited on the monolog projet : see https://github.com/Seldaek/monolog .  

As far as I can see, I think the only way to do this would be to create new LogRecord instance with the adequate datetime and then pass those records to the LokiHandler::handleBatch method.

However this is something I've never attempted so this is purely theoretical.

**Comment by l2aelba** [comment]
Thanks @rrajkomar , this issue is not about monolog-loki.

Because we cannot push the custom date more than 1 hour.

![Screenshot 2024-09-27 at 14 50 52](https://github.com/user-attachments/assets/2034d7e0-5a7b-4e64-b4b6-eb743e4fd343)

https://grafana.com/blog/2024/01/04/the-concise-guide-to-loki-how-to-work-with-out-of-order-and-older-logs/

Closed.
