### ISSUE TITLE
Best practice - log level as default label 

### ISSUE THREAD

**Issue by aakarim** [itspire/monolog-loki#9]
Hi, thank you for the library.

One thing I've found is that this library adds a default label called 'level_name', this is discouraged by best practices: https://grafana.com/docs/loki/latest/best-practices/

Perhaps this could be removed?

**Comment by rrajkomar** [comment]
I need to take a look to be sure but I believe I added this one because the default level column used by Loki is not working properly with Monolog.
I'll get back to this issue when I have checked.
